ci: update

diff --git a/.github/workflows/CICD.yaml b/.github/workflows/CICD.yaml
--- a/.github/workflows/CICD.yaml
+++ b/.github/workflows/CICD.yaml
@@ -15,11 +15,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
       - name: Go mod download
@@ -35,11 +35,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
           cache: false
@@ -64,11 +64,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
           cache: false
@@ -93,11 +93,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
           cache: false
@@ -122,11 +122,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
 # # # # # TODO Setup linting
@@ -153,11 +153,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
       - name: Cache libvips ffmpeg
@@ -190,11 +190,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
       - name: Cache libvips ffmpeg
@@ -232,11 +232,11 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
       - name: Cache libvips ffmpeg
@@ -300,11 +300,11 @@ jobs:
     permissions: write-all
     steps:
       - name: Checkout
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           fetch-depth: 0
       - name: Setup GO
-        uses: actions/setup-go@v5
+        uses: actions/setup-go@v6
         with:
           go-version-file: go.mod
       - name: Cache libvips ffmpeg
@@ -317,7 +317,7 @@ jobs:
         run: env GOOS=linux env GOARCH=amd64 make buildAllBinaries
       - name: Compute new Tag version
         id: compute_tag
-        uses: craig-day/compute-tag@v14
+        uses: craig-day/compute-tag@v18
         with:
           github_token: ${{ github.token }}
           version_type: minor
@@ -369,47 +369,37 @@ jobs:
         run: |
           echo "APP_TAG=${{needs.release.outputs.nextTag}}" >> $GITHUB_ENV
       - name: Checkout the target `master` branch of `secret-infrastructure`
-        uses: actions/checkout@v4
+        uses: actions/checkout@v6
         with:
           repository: ice-blockchain/secret-infrastructure
           ref: master
           token: ${{ secrets.ICE_CI_CD_BOT_GH_PAT }}
           path: secret-infrastructure
           fetch-depth: 0
-      - name: Update [staging] application tag version in helm/subzero-ion-connect/staging/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
+      - name: Update application tag versions
+        run: |
+            SERVICES="subzero-ion-connect subzero-ion-connect-indexer"
+            ENVIRONMENTS="staging testnet"
+            set -xe
             cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/subzero-ion-connect/staging/common-values.yaml
-      - name: Update [staging] application tag version in helm/subzero-ion-connect-indexer/staging/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/subzero-ion-connect-indexer/staging/common-values.yaml
-      - name: Update [testnet] application tag version in helm/subzero-ion-connect/testnet/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/subzero-ion-connect/testnet/common-values.yaml
-      - name: Update [testnet] application tag version in helm/subzero-ion-connect-indexer/testnet/common-values.yaml
-        uses: mikefarah/yq@master
-        with:
-          cmd: |
-            cd secret-infrastructure
-            yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' helm/subzero-ion-connect-indexer/testnet/common-values.yaml
+            for SERVICE in ${SERVICES}; do
+              for ENV in ${ENVIRONMENTS}; do
+                FILE_PATH="helm/${SERVICE}/${ENV}/common-values.yaml"
+                echo "Updating ${FILE_PATH}..."
+                if [ -f "$FILE_PATH" ]; then
+                  yq e -i '.generic-service-chart.applicationImage.tag = strenv(APP_TAG)' "${FILE_PATH}"
+                  git add "${FILE_PATH}"
+                else
+                  echo "Warning: ${FILE_PATH} not found, skipping"
+                fi
+              done
+            done
       - name: Commit and Push Changes to Application Tag Version
         run: |
           cd secret-infrastructure
           git config user.name "ice CI/CD Bot"
           git config user.email ice-cicd-bot@ice.vip
-          git add helm/subzero-ion-connect/staging/common-values.yaml
-          git add helm/subzero-ion-connect-indexer/staging/common-values.yaml
-          git add helm/subzero-ion-connect/testnet/common-values.yaml
-          git add helm/subzero-ion-connect-indexer/testnet/common-values.yaml
-          git commit -m "Updated 'subzero-ion-connect' & 'subzero-ion-connect-indexer' tag version (${{env.APP_TAG}}) in application helm chart deployment manifests"
+          git commit -m "Updated 'subzero' tag version (${{env.APP_TAG}}) in application helm chart deployment manifests"
           git push --set-upstream origin master
       - name: Slack Notification For Success
         if: ${{ success() }}
